version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      # --- Connection Variables for Entrypoint Script ---
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      # --- Django Connection String ---
      DATABASE_URL: "postgres://postgres:postgres@db:5432/horilla"
      DJANGO_SETTINGS_MODULE: "horilla.settings"
    volumes:
      - ./horilla:/horilla
      - ./media:/horilla/media
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-bullseye
    environment:
      POSTGRES_DB: horilla
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - horilla-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  horilla-data: